//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.21 at 01:56:52 AM IRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mohamad97mj.com/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ir.co.pna.exchange.client.country.generated_resources;
