//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.06 at 01:42:25 PM IRDT 
//


package ir.co.pna.exchange.client.yaghut2.generated_resources;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ir.co.pna.exchange.client.yaghut2.generated_resources package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ir.co.pna.exchange.client.yaghut2.generated_resources
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NormalTransfer }
     * 
     */
    public NormalTransfer createNormalTransfer() {
        return new NormalTransfer();
    }

    /**
     * Create an instance of {@link NormalTransferResponse }
     * 
     */
    public NormalTransferResponse createNormalTransferResponse() {
        return new NormalTransferResponse();
    }

    /**
     * Create an instance of {@link Statement }
     * 
     */
    public Statement createStatement() {
        return new Statement();
    }

    /**
     * Create an instance of {@link StatementResponse }
     * 
     */
    public StatementResponse createStatementResponse() {
        return new StatementResponse();
    }

    /**
     * Create an instance of {@link StatementResponseBean }
     * 
     */
    public StatementResponseBean createStatementResponseBean() {
        return new StatementResponseBean();
    }

    /**
     * Create an instance of {@link StatementBean }
     * 
     */
    public StatementBean createStatementBean() {
        return new StatementBean();
    }

}
