//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.24 at 06:52:50 PM IRST 
//


package ir.co.pna.exchange.client.sms.generated_resources;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SMS_Gateway.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SMS_Gateway"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ADVERTISEMENT"/&gt;
 *     &lt;enumeration value="PAYMENT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SMS_Gateway")
@XmlEnum
public enum SMSGateway {

    ADVERTISEMENT,
    PAYMENT;

    public String value() {
        return name();
    }

    public static SMSGateway fromValue(String v) {
        return valueOf(v);
    }

}
