package ir.co.pna.exchange.emum;

public enum ContractStatus {
    NONE,
    WAITING_FOR_EXCHANGER_ACCEPTANCE,
    WAITING_FOR_EXPORTER_ACCEPTANCE,
    WAITING_FOR_IMPORTER_PAYMENT,
    WAITING_FOR_EXCHANGER_PAYMENT,
    REJECTED_BY_EXCHANGER,
    REJECTED_BY_EXPORTER,
    DOING_BY_EXCHANGER,
    DOING_BY_EXPORTER,
    WAITING_FOR_IMPORTER_CONFIRMATION,
    WAITING_FOR_EXCHANGER_CONFIRMATION,
    WAITING_FOR_PARENT,
    CONFIRMED_BY_EXCHANGER,
    DENIED_BY_EXCHANGER,
    CONFIRMED_BY_IMPORTER,
    CLAIMED_BY_IMPORTER,
    JUDGED,
}
