//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.24 at 06:53:55 PM IRST 
//


package ir.co.pna.exchange.client.yaghut.generated_resources;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ir.co.pna.exchange.client.yaghut.generated_resources package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ir.co.pna.exchange.client.yaghut.generated_resources
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACH }
     * 
     */
    public ACH createACH() {
        return new ACH();
    }

    /**
     * Create an instance of {@link ACHResponse }
     * 
     */
    public ACHResponse createACHResponse() {
        return new ACHResponse();
    }

    /**
     * Create an instance of {@link RTGS }
     * 
     */
    public RTGS createRTGS() {
        return new RTGS();
    }

    /**
     * Create an instance of {@link RTGSResponse }
     * 
     */
    public RTGSResponse createRTGSResponse() {
        return new RTGSResponse();
    }

    /**
     * Create an instance of {@link ChangePassword }
     * 
     */
    public ChangePassword createChangePassword() {
        return new ChangePassword();
    }

    /**
     * Create an instance of {@link ChangePasswordResponse }
     * 
     */
    public ChangePasswordResponse createChangePasswordResponse() {
        return new ChangePasswordResponse();
    }

    /**
     * Create an instance of {@link InstituteTransfer }
     * 
     */
    public InstituteTransfer createInstituteTransfer() {
        return new InstituteTransfer();
    }

    /**
     * Create an instance of {@link InstituteTransferResponse }
     * 
     */
    public InstituteTransferResponse createInstituteTransferResponse() {
        return new InstituteTransferResponse();
    }

    /**
     * Create an instance of {@link NormalTransfer }
     * 
     */
    public NormalTransfer createNormalTransfer() {
        return new NormalTransfer();
    }

    /**
     * Create an instance of {@link NormalTransferResponse }
     * 
     */
    public NormalTransferResponse createNormalTransferResponse() {
        return new NormalTransferResponse();
    }

}
